Repository university-admission/admissio-scraper, pull requests merged in 2025-07, with the labels that each got.

#1 feat: maven init
  .gitattributes
  .gitignore
  .mvn/wrapper/maven-wrapper.properties
  README.md
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/org/admissio/scraper/ScraperApplication.java
  src/main/java/org/admissio/scraper/controller/PingController.java
  src/main/resources/application.properties
  src/test/java/org/admissio/scraper/ScraperApplicationTests.java
Labels: enhancement

#4 feat: docker init
  .dockerignore
  .gitignore
  Dockerfile
  README.md
Labels: documentation, enhancement

#9 feat: add UniversityRegion table, faculty field in Offer
  src/main/java/org/admissio/scraper/Entity/Offer.java
  src/main/java/org/admissio/scraper/Entity/University.java
  src/main/java/org/admissio/scraper/Entity/UniversityRegion.java
Labels: enhancement

#10 fix: table bug with not nullable fields
  src/main/java/org/admissio/scraper/Entity/Major.java
  src/main/java/org/admissio/scraper/Entity/Offer.java
  src/main/java/org/admissio/scraper/Entity/UniversityRegion.java
Labels: bug

#17 fix: table bug with not nullable fields
  src/main/java/org/admissio/scraper/Entity/Application.java
  src/main/java/org/admissio/scraper/Entity/Major.java
  src/main/java/org/admissio/scraper/Entity/Offer.java
  src/main/java/org/admissio/scraper/Entity/University.java
  src/main/java/org/admissio/scraper/Entity/UniversityRegion.java
Labels: bug

#18 Add sql files with basic data
  pom.xml
  src/main/java/org/admissio/scraper/controller/ApplicationController.java
  src/main/java/org/admissio/scraper/entity/Application.java
  src/main/java/org/admissio/scraper/entity/Major.java
  src/main/java/org/admissio/scraper/entity/Offer.java
  src/main/java/org/admissio/scraper/entity/Student.java
  src/main/java/org/admissio/scraper/entity/University.java
  src/main/java/org/admissio/scraper/entity/UniversityRegion.java
  src/main/java/org/admissio/scraper/service/ApplicationService.java
  src/main/resources/db/migration/V1__applications_data.sql
  src/main/resources/db/migration/V1__majors_data.sql
  src/main/resources/db/migration/V1__students_data.sql
  src/main/resources/db/migration/V1__universities_data.sql
  src/main/resources/db/migration/V1__university_regions_data.sql
  src/main/resources/db/migration/V1_offers_data.sql
  src/main/resources/db/migration/delete_db_data.sql
Labels: enhancement

#19 Bezukh_main
  pom.xml
  src/main/java/org/admissio/scraper/controller/ApplicationController.java
  src/main/java/org/admissio/scraper/controller/PingController.java
  src/main/java/org/admissio/scraper/controller/TempAnalyserController.java
  src/main/java/org/admissio/scraper/entity/Application.java
  src/main/java/org/admissio/scraper/entity/Major.java
  src/main/java/org/admissio/scraper/entity/QuotaType.java
  src/main/java/org/admissio/scraper/repository/ApplicationRepository.java
  src/main/java/org/admissio/scraper/repository/MajorRepository.java
  src/main/java/org/admissio/scraper/repository/OfferRepository.java
  src/main/java/org/admissio/scraper/repository/StudentRepository.java
  src/main/java/org/admissio/scraper/repository/UniversityRegionRepository.java
  src/main/java/org/admissio/scraper/repository/UniversityRepository.java
  src/main/java/org/admissio/scraper/service/AnalyserService.java
  src/main/java/org/admissio/scraper/service/ApplicationKey.java
  src/main/java/org/admissio/scraper/service/StudentApplicationKey.java
  src/main/resources/application-local.properties
  src/main/resources/application.properties
  src/main/resources/db/migration/V1__applications_data.sql
  src/main/resources/db/migration/V1__create_university_regions.sql
  src/main/resources/db/migration/V1__majors_data.sql
  src/main/resources/db/migration/V1__students_data.sql
  src/main/resources/db/migration/V1__universities_data.sql
  src/main/resources/db/migration/V1__university_regions_data.sql
  src/main/resources/db/migration/V1_offers_data.sql
  src/main/resources/db/migration/V2__create_universities.sql
  src/main/resources/db/migration/V3__create_majors.sql
  src/main/resources/db/migration/V4__create_students.sql
  src/main/resources/db/migration/V5__create_offers.sql
  src/main/resources/db/migration/V6__create_applications.sql
  src/main/resources/db/migration/V7__seed_university_regions.sql
  src/main/resources/db/migration/V8__seed_universities.sql
  src/main/resources/db/migration/V9__seed_majors.sql
  src/main/resources/db/migration/delete_db_data.sql
Labels: enhancement

#24 Finish basic single thread scraper for db
  src/main/java/org/admissio/scraper/controller/TempAnalyserController.java
  src/main/java/org/admissio/scraper/dto/application/ApplicationDto.java
  src/main/java/org/admissio/scraper/dto/application/EdboApplicationResponseWrapper.java
  src/main/java/org/admissio/scraper/dto/application/RssEntryDto.java
  src/main/java/org/admissio/scraper/dto/offer/EdboResponseWrapper.java
  src/main/java/org/admissio/scraper/dto/offer/OfferDetailsDto.java
  src/main/java/org/admissio/scraper/dto/offer/ScoreStatisticsDto.java
  src/main/java/org/admissio/scraper/dto/offer/SubjectDetailsDto.java
  src/main/java/org/admissio/scraper/dto/university/EdboUniversityResponseWrapper.java
  src/main/java/org/admissio/scraper/dto/university/UniversityDto.java
  src/main/java/org/admissio/scraper/entity/Application.java
  src/main/java/org/admissio/scraper/entity/Major.java
  src/main/java/org/admissio/scraper/entity/Offer.java
  src/main/java/org/admissio/scraper/entity/Student.java
  src/main/java/org/admissio/scraper/entity/UniversityRegion.java
  src/main/java/org/admissio/scraper/repository/MajorRepository.java
  src/main/java/org/admissio/scraper/repository/UniversityRepository.java
  src/main/java/org/admissio/scraper/service/AnalyserService.java
  src/main/java/org/admissio/scraper/service/ApplicationService.java
  src/main/java/org/admissio/scraper/service/BatchSavingService.java
  src/main/java/org/admissio/scraper/service/MajorService.java
  src/main/java/org/admissio/scraper/service/OfferService.java
  src/main/java/org/admissio/scraper/service/ScraperService.java
  src/main/java/org/admissio/scraper/service/StudentService.java
  src/main/java/org/admissio/scraper/service/UniversityRegionService.java
  src/main/java/org/admissio/scraper/service/UniversityService.java
  src/main/java/org/admissio/scraper/utils/WebClientInsecure.java
  src/main/resources/db/migration/V1__create_university_regions.sql
  src/main/resources/db/migration/V4__create_students.sql
  src/main/resources/db/migration/V6__create_applications.sql
  src/main/resources/db/migration/V7__seed_university_regions.sql
Labels: enhancement, help wanted, invalid
